ARG ARCH=
FROM ${ARCH}node:16.14.0-buster AS build
WORKDIR /app
ENV DOCKER=YES NODE_ENV=production
ADD . .

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        make \
        gcc \
        g++ \
        pkg-config \
        pcscd \
        libpcsclite-dev \
        libccid \
        libdvbv5-dev \
        pcsc-tools \
        dvb-tools \
        && \
# recpt1
\
    apt-get install -y --no-install-recommends \
        build-essential \
        libtool \
        autoconf \
        git \
        automake &&\
    git clone https://github.com/stz2012/recpt1 /tmp/recpt1 && \
    cd /tmp/recpt1/recpt1 && \
    ./autogen.sh && \
    ./configure --enable-b25　&& \
    make && \
    make install && \
#    rm -rf /tmp/recpt1 && \
    apt-get autoremove -y && \

    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY --from=build /usr/local/lib/node_modules/mirakurun /app
CMD ["./docker/container-init.sh"]
EXPOSE 40772 9229
